import { PROGRAMS, TASK_TYPES } from './programs';
import { withLepResources } from './lepResources';

/** Real LMS phase + task ids. Content from the web LMS course lists. */

export const COURSE_PHASES = {
  [PROGRAMS.LEP]: [
    { id: 'pre-program', title: 'Pre-Program Preparation', sub: '3 lessons · before Day 1', openRegistered: true },
    { id: 'orientation', title: 'Program Orientation', sub: '3 lessons · before Day 1', openRegistered: true },
    { id: 'day-1', title: 'Day 1 — Personal Transformation', sub: '6 lessons · Week 1', openRegistered: true },
    { id: 'day-2', title: 'Day 2 — Strategies and Tactics', sub: '6 lessons · Week 1', openRegistered: false },
    { id: 'week-1', title: 'Week 1 — Consolidation and Closure', sub: '5 lessons · Week 1', openRegistered: false },
    { id: 'week-2', title: 'Week 2 — Profile, Resume and Pitch', sub: '14 lessons · Week 2', openRegistered: false },
    { id: 'week-3', title: 'Week 3 — Progress Review and Guiding Stars', sub: '5 lessons · Week 3', openRegistered: false },
    { id: 'week-4', title: 'Week 4 — Graduation', sub: '6 lessons · Week 4', openRegistered: false },
    { id: 'community', title: 'Community Sessions', sub: '2 lessons · ongoing', openRegistered: false },
    { id: 'evaluation', title: 'Final Evaluation', sub: '2 lessons · Week 4', openRegistered: false },
    { id: 'certificate', title: 'Certificate', sub: '2 lessons · on completion', openRegistered: false },
  ],
  [PROGRAMS.BM100]: [
    { id: 'onboarding', title: 'Onboarding', sub: '2 lessons · before Week 1', openRegistered: true },
    { id: 'phase-1-foundation', title: 'Phase 1 — Foundation', sub: '8 lessons · Wk1–Wk8', openRegistered: false },
    { id: 'phase-2-pitch-strategy', title: 'Phase 2 — Pitch & Strategy', sub: '6 lessons · Wk9–Wk14', openRegistered: false },
    { id: 'phase-3-board-ready', title: 'Phase 3 — Board Ready', sub: '3 lessons · Wk15–Wk17', openRegistered: false },
    { id: 'phase-4-challenges', title: 'Phase 4 — Challenges', sub: '6 lessons · Wk18–Wk23', openRegistered: false },
    { id: 'graduation', title: 'Graduation', sub: '1 lesson · Wk24', openRegistered: false },
  ],
  [PROGRAMS.MBW]: [
    { id: 'pre-preparation', title: 'Pre-Preparation', sub: '12 lessons · before the cohort', openRegistered: true },
    { id: 'quarter-1', title: 'Quarter 1', sub: '17 lessons · Wk1–Wk12', openRegistered: false },
    { id: 'quarter-2', title: 'Quarter 2', sub: '17 lessons · Wk13–Wk24', openRegistered: false },
    { id: 'quarter-3', title: 'Quarter 3', sub: '17 lessons · Wk25–Wk36', openRegistered: false },
    { id: 'quarter-4', title: 'Quarter 4', sub: '17 lessons · Wk37–Wk48', openRegistered: false },
    { id: 'graduation', title: 'Graduation', sub: '5 lessons · Wk49–Wk52', openRegistered: false },
  ],
};

export const COURSE_TASKS = {
  [PROGRAMS.LEP]: withLepResources([
    {
      id: "lep-via-survey",
      phase: "pre-program",
      order: 0,
      title: "Complete your VIA Survey and Submit your 3 Photographs",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Register and complete the VIA Character Survey, then upload your free survey report. Your individualised excellence profile depends on this — it cannot be produced without your report.",
      week: "Prep",
    },
    {
      id: "lep-prep-codesef-sheet",
      phase: "pre-program",
      order: 1,
      title: "Fill the CoDeSeF Sheet",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "codesef",
      kind: "Form",
      description: "Fill in your CoDeSeF sheet before Day 1. Work through the four steps in order — each one builds on the step above it.",
      week: "Prep",
    },
    {
      id: "lep-prep-nsdc",
      phase: "pre-program",
      order: 2,
      title: "Complete NSDC Registration",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Complete your NSDC registration and submit the confirmation link.",
      week: "Prep",
    },
    {
      id: "lep-orientation-framework",
      phase: "orientation",
      order: 100,
      title: "Program Framework",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Read the programme framework and confirm you know how the four weeks are structured.",
      week: "Start",
      checklistItems: ["I have read the programme framework","I know which days are live sessions","I know what is expected of me each week"],
    },
    {
      id: "lep-orientation-access",
      phase: "orientation",
      order: 101,
      title: "Program Access Essentials",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Set up your access so nothing blocks you on Day 1.",
      week: "Start",
      checklistItems: ["I can sign in to the programme","I have joined the community group","I have the session joining details"],
    },
    {
      id: "lep-orientation-schedule",
      phase: "orientation",
      order: 102,
      title: "Program Schedule",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Check your batch dates on the calendar and block them out.",
      week: "Start",
      checklistItems: ["I have blocked out all session dates in my own calendar"],
    },
    {
      id: "lep-day1-promises",
      phase: "day-1",
      order: 200,
      title: "Promises and Agreements",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Read the promises and agreements for the programme and sign them.",
      week: "Day 1",
      checklistItems: ["I have read and signed the promises and agreements"],
    },
    {
      id: "lep-day1-beliefs",
      phase: "day-1",
      order: 201,
      title: "A-Game Self Awareness — Beliefs",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "agame-beliefs",
      kind: "Form",
      description: "Work through the beliefs questionnaire and answer every question. This is what enables you to play your A-Game.",
      week: "Day 1",
    },
    {
      id: "lep-day1-agame-table",
      phase: "day-1",
      order: 202,
      title: "A-Game Table — daily ritual",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "agame-table",
      kind: "Form",
      description: "Fill in your A-Game table for today: the moments you were at your best, and the moments you were not.",
      week: "Day 1",
    },
    {
      id: "lep-day1-errc",
      phase: "day-1",
      order: 203,
      title: "ERRC Table",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "errc",
      kind: "Form",
      description: "Complete your ERRC table below — what you will Eliminate, Reduce, Raise and Create. Fill every block before submitting.",
      week: "Day 1",
    },
    {
      id: "lep-day1-crucible",
      phase: "day-1",
      order: 204,
      title: "Crucibles of Leadership",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "crucible",
      kind: "Form",
      description: "Read each question, close your eyes and ask it of yourself, then open your eyes and write your answer. Work through all five in the same way before writing your statement.",
      week: "Day 1",
    },
    {
      id: "lep-day1-assignment",
      phase: "day-1",
      order: 205,
      title: "Day 1 Assignment",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Download the Day 1 assignment, answer all questions and upload your completed work.",
      week: "Day 1",
    },
    {
      id: "lep-day2-codesef",
      phase: "day-2",
      order: 300,
      title: "CoDeSeF",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "codesef",
      kind: "Form",
      description: "Iron Lady’s technique for strategising towards your BHAG. Work through the four steps in order — each one builds on the step above it.",
      week: "Day 2",
    },
    {
      id: "lep-day2-responding",
      phase: "day-2",
      order: 301,
      title: "Powerful Extreme Responding",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "responding",
      kind: "Form",
      description: "For each situation, mark whether you respond or react. The total shows your pattern.",
      week: "Day 2",
    },
    {
      id: "lep-day2-relationships",
      phase: "day-2",
      order: 302,
      title: "Maximise Key Relationships",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "key-relationships",
      kind: "Form",
      description: "Identify your key relationships and how you will strengthen each one.",
      week: "Day 2",
    },
    {
      id: "lep-day2-purpose-peg",
      phase: "day-2",
      order: 303,
      title: "Purpose Peg Table",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "purpose-peg",
      kind: "Form",
      description: "Complete your Purpose Peg table. The samples show the level of detail expected.",
      week: "Day 2",
    },
    {
      id: "lep-day2-assignment",
      phase: "day-2",
      order: 304,
      title: "Day 2 Assignment",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Download the Day 2 assignment, answer all questions and upload your work.",
      week: "Day 2",
    },
    {
      id: "lep-day3-feedback",
      phase: "day-2",
      order: 305,
      title: "Feedback for Days 1–2",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Share your feedback on the first three days.",
      week: "Day 3",
    },
    {
      id: "lep-day4-roadmap-sample",
      phase: "week-1",
      order: 400,
      title: "0.5% League Roadmap — worked sample",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Study the worked sample before building your own roadmap.",
      week: "Day 4",
      checklistItems: ["I have studied the sample roadmap"],
    },
    {
      id: "lep-day4-roadmap",
      phase: "week-1",
      order: 401,
      title: "Your 0.5% League Roadmap",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      templateId: "league-roadmap",
      kind: "Form",
      description: "Build your own 0.5% League roadmap. The worked sample shows the level of detail expected.",
      week: "Day 4",
    },
    {
      id: "lep-day4-feedback",
      phase: "week-1",
      order: 402,
      title: "Feedback — Differentiated Brand Statement",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Share your feedback on Day 4.",
      week: "Day 4",
    },
    {
      id: "lep-weekly-1",
      phase: "week-1",
      order: 480,
      title: "Week 1 Engagement Form",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Complete the week 1 engagement form.",
      week: "Week 1",
    },
    {
      id: "lep-challenge-1",
      phase: "week-1",
      order: 490,
      title: "Challenge for Week 1",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Game of Excellence — complete the week 1 challenge and tell us how it went.",
      week: "Week 1",
    },
    {
      id: "lep-day3-27-principles",
      phase: "week-2",
      order: 500,
      title: "27 Principles",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Watch the 27 Principles session and note the ones you will act on.",
      week: "Day 3",
      checklistItems: ["I have watched the 27 Principles session"],
    },
    {
      id: "lep-day3-5-rituals",
      phase: "week-2",
      order: 501,
      title: "Practising the 5 Rituals",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Start the five daily rituals and keep them going.",
      week: "Day 3",
      checklistItems: ["I know all five rituals","I have started practising them daily"],
    },
    {
      id: "lep-day3-brand-roadmap",
      phase: "week-2",
      order: 502,
      title: "Differentiated Brand and the 0.5% League Roadmap",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Understand how to use your differentiated brand to build your 0.5% League roadmap.",
      week: "Day 3",
      checklistItems: ["I understand how to build my 0.5% League roadmap"],
    },
    {
      id: "lep-day3-mentors",
      phase: "week-2",
      order: 503,
      title: "Finding and Working with Mentors",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Name the mentors you will approach and what you will ask of each.",
      week: "Day 3",
    },
    {
      id: "lep-day3-max-value",
      phase: "week-2",
      order: 504,
      title: "Getting Maximum Value from LEP",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Know what the programme offers beyond the sessions and how to use it.",
      week: "Day 3",
      checklistItems: ["I know how to get the most from this programme"],
    },
    {
      id: "lep-resume-linkedin",
      phase: "week-2",
      order: 505,
      title: "Build your LinkedIn Profile",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Rebuild your LinkedIn profile, then share the link to it.",
      week: "Week 2",
    },
    {
      id: "lep-resume-template-study",
      phase: "week-2",
      order: 506,
      title: "Resume Template and Samples",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Study the Iron Lady resume format before writing your own.",
      week: "Week 2",
      checklistItems: ["I have studied the resume template and samples"],
    },
    {
      id: "lep-resume-bootcamp",
      phase: "week-2",
      order: 507,
      title: "Jobseekers Bootcamp",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Watch the Jobseekers Bootcamp recording.",
      week: "Week 2",
      checklistItems: ["I have watched the bootcamp recording"],
    },
    {
      id: "lep-resume-prepare",
      phase: "week-2",
      order: 508,
      title: "Prepare your Resume",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Write your resume using the Iron Lady format and upload it.",
      week: "Week 2",
    },
    {
      id: "lep-day5-instructions",
      phase: "week-2",
      order: 509,
      title: "Shameless Pitch — preparation",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Read the preparation instructions and the key points before you pitch.",
      week: "Day 5",
      checklistItems: ["I have read the preparation instructions","I have read the key points"],
    },
    {
      id: "lep-day5-pitch",
      phase: "week-2",
      order: 510,
      title: "Your Shameless Pitch",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record and submit your shameless pitch.",
      week: "Day 5",
    },
    {
      id: "lep-day5-feedback",
      phase: "week-2",
      order: 511,
      title: "Feedback — Shameless Pitching",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Share your feedback on the pitching session.",
      week: "Day 5",
    },
    {
      id: "lep-weekly-2",
      phase: "week-2",
      order: 580,
      title: "Week 2 Engagement Form",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Complete the week 2 engagement form.",
      week: "Week 2",
    },
    {
      id: "lep-challenge-2",
      phase: "week-2",
      order: 590,
      title: "Challenge for Week 2",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Game of Excellence — complete the week 2 challenge and tell us how it went.",
      week: "Week 2",
    },
    {
      id: "lep-day7-review",
      phase: "week-3",
      order: 600,
      title: "Progress Review",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Review your progress across the programme so far — what has changed, and what is still open.",
      week: "Day 7",
    },
    {
      id: "lep-day6-guiding-stars",
      phase: "week-3",
      order: 601,
      title: "Guiding Stars",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Identify your guiding stars and what each one means for your next step.",
      week: "Day 6",
    },
    {
      id: "lep-day6-feedback",
      phase: "week-3",
      order: 602,
      title: "Feedback — Guiding Stars",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Share your feedback on Day 6.",
      week: "Day 6",
    },
    {
      id: "lep-weekly-3",
      phase: "week-3",
      order: 680,
      title: "Week 3 Engagement Form",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Complete the week 3 engagement form.",
      week: "Week 3",
    },
    {
      id: "lep-challenge-3",
      phase: "week-3",
      order: 690,
      title: "Challenge for Week 3",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Game of Excellence — complete the week 3 challenge and tell us how it went.",
      week: "Week 3",
    },
    {
      id: "lep-day8-preparation",
      phase: "week-4",
      order: 700,
      title: "Graduation Preparations",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Prepare for graduation day.",
      week: "Day 8",
      checklistItems: ["I have completed my graduation preparations"],
    },
    {
      id: "lep-day8-alumni",
      phase: "week-4",
      order: 701,
      title: "Join the Iron Lady Alumni",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Join the Iron Lady Alumni network on LinkedIn and share your profile link.",
      week: "Day 8",
    },
    {
      id: "lep-day8-feedback",
      phase: "week-4",
      order: 702,
      title: "Graduation Feedback",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Share your feedback on the programme.",
      week: "Day 8",
    },
    {
      id: "lep-weekly-4",
      phase: "week-4",
      order: 780,
      title: "Week 4 Engagement Form",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Complete the week 4 engagement form.",
      week: "Week 4",
    },
    {
      id: "lep-weekly-5",
      phase: "week-4",
      order: 781,
      title: "Week 5 Engagement Form",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Complete the week 5 engagement form.",
      week: "Week 5",
    },
    {
      id: "lep-challenge-4",
      phase: "week-4",
      order: 790,
      title: "Challenge for Week 4",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Game of Excellence — complete the week 4 challenge and tell us how it went.",
      week: "Week 4",
    },
    {
      id: "lep-community-schedule",
      phase: "community",
      order: 800,
      title: "Community Sessions Schedule",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Check the community session schedule and attend what applies to you.",
      week: "Ongoing",
      checklistItems: ["I know when the community sessions run"],
    },
    {
      id: "lep-community-handholding",
      phase: "community",
      order: 801,
      title: "Weekly Handholding Sessions",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "See what the weekly handholding sessions cover for the Iron Lady community.",
      week: "Ongoing",
      checklistItems: ["I know what the handholding sessions offer"],
    },
    {
      id: "lep-quiz-5-rituals",
      phase: "evaluation",
      order: 900,
      title: "5 Daily Rituals — Quiz",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Complete the 5 Daily Rituals quiz.",
      week: "Week 4",
      checklistItems: ["I have completed the 5 Daily Rituals quiz"],
    },
    {
      id: "lep-quiz-27-principles",
      phase: "evaluation",
      order: 901,
      title: "27 Principles — Quiz",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Complete the 27 Principles quiz.",
      week: "Week 4",
      checklistItems: ["I have completed the 27 Principles quiz"],
    },
    {
      id: "lep-attendance",
      phase: "certificate",
      order: 1000,
      title: "Attendance",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Confirm your attendance record is complete.",
      week: "Close",
      checklistItems: ["My attendance record is complete"],
    },
    {
      id: "lep-certification",
      phase: "certificate",
      order: 1001,
      title: "LEP Certification",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Collect your Leadership Essentials Program certificate.",
      week: "Close",
      checklistItems: ["I have collected my certificate"],
    },
  ]),
  [PROGRAMS.BM100]: [
    {
      id: "bm100-wk1-4",
      phase: "onboarding",
      order: 0,
      title: "Core Story Practice Session",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete both core brand stories below — fill every block before submitting.",
      week: "Prep 1",
    },
    {
      id: "bm100-wk1-1",
      phase: "onboarding",
      order: 1,
      title: "Milestone Table Practice Session",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your Delta / Milestone Table below — fill every block before submitting.",
      week: "Prep 2",
    },
    {
      id: "bm100-onb-brand-video",
      phase: "onboarding",
      order: 1.1,
      title: "Brand Creation Video",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record your Core Story on camera — 2 to 3 minutes. Imperfect is fine; you will rework it in Phase 1.",
      week: "Prep 3",
    },
    {
      id: "bm100-onb-resume",
      phase: "onboarding",
      order: 1.2,
      title: "Resume Preparation",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Upload",
      description: "Upload a current draft of your resume. You will rework it with your mentor in Phase 1.",
      week: "Prep 3",
    },
    {
      id: "bm100-wk1",
      phase: "phase-1-foundation",
      order: 2,
      title: "Session 1 — Board Member Image Creation",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your Core Brand Video Script below using the IL format — fill every block before submitting.",
      week: "Wk1",
    },
    {
      id: "bm100-wk2",
      phase: "phase-1-foundation",
      order: 3,
      title: "Imperfect Brand Video Session",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record or upload your Imperfect Brand Video.",
      week: "Wk2",
    },
    {
      id: "bm100-wk3",
      phase: "phase-1-foundation",
      order: 4,
      title: "Resume and Differentiated Brand",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Upload your updated CV and ensure your LinkedIn profile is refreshed.",
      week: "Wk3",
    },
    {
      id: "bm100-wk4",
      phase: "phase-1-foundation",
      order: 5,
      title: "Session 2 — Mid Level Performance Excellence",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your ERRC Table after the session — fill every block before submitting.",
      week: "Wk4",
    },
    {
      id: "bm100-wk5",
      phase: "phase-1-foundation",
      order: 6,
      title: "Theme Management",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your Theme Table below — fill every block before submitting.",
      week: "Wk5",
    },
    {
      id: "bm100-wk6",
      phase: "phase-1-foundation",
      order: 7,
      title: "Pre Session on Capability Matrix",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "List your top 3 super powers (check with people around you) and top 3 capabilities you need to develop.",
      week: "Wk6",
      placeholder: "Super powers and capabilities to develop…",
    },
    {
      id: "bm100-wk7",
      phase: "phase-1-foundation",
      order: 8,
      title: "Session 3 — Leadership Super Power & Capability Matrix",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record your Capability Demonstration Video — read a book and speak like the author of the book.",
      week: "Wk7",
    },
    {
      id: "bm100-wk8",
      phase: "phase-1-foundation",
      order: 9,
      title: "Post Session on Capability Matrix",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Submit a video or voice recording about 1 learning through the Capability Development Framework.",
      week: "Wk8",
    },
    {
      id: "bm100-wk9",
      phase: "phase-2-pitch-strategy",
      order: 10,
      title: "Pre-Session on Pitch",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your pitch document below (Scenario → Threat/Opportunity → Solution → Credibility) before the session.",
      week: "Wk9",
    },
    {
      id: "bm100-wk10",
      phase: "phase-2-pitch-strategy",
      order: 11,
      title: "Session 4 — Pitching and Influencing Tactics",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Submit your pitch video from the session.",
      week: "Wk10",
    },
    {
      id: "bm100-wk11",
      phase: "phase-2-pitch-strategy",
      order: 12,
      title: "Post-Session on Pitch",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record your pitch video using the framework — Scenario → Threat/Opportunity → Solution → Credibility.",
      week: "Wk11",
    },
    {
      id: "bm100-wk12",
      phase: "phase-2-pitch-strategy",
      order: 13,
      title: "Pre-Session on Mid Level Politics",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete the strategy problem statement (first 5 points) below — fill every block before submitting.",
      week: "Wk12",
    },
    {
      id: "bm100-wk13",
      phase: "phase-2-pitch-strategy",
      order: 14,
      title: "Session 5 — Mid-Level Politics Management",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your full strategy document below — fill every required block before submitting.",
      week: "Wk13",
    },
    {
      id: "bm100-wk14",
      phase: "phase-2-pitch-strategy",
      order: 15,
      title: "Post-Session on Politics Management",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Update your strategy document below after feedback — fill every required block before submitting.",
      week: "Wk14",
    },
    {
      id: "bm100-wk16",
      phase: "phase-3-board-ready",
      order: 16,
      title: "Session 6 — Strategic Outlook",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Submit a video of you speaking as a CEO in a townhall.",
      week: "Wk15",
    },
    {
      id: "bm100-strategy-review",
      phase: "phase-3-board-ready",
      order: 17,
      title: "Strategy Review Session",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Update your strategy document below after live feedback — fill every required block before submitting.",
      week: "Wk16",
    },
    {
      id: "bm100-wk17",
      phase: "phase-3-board-ready",
      order: 18,
      title: "Mock Interview",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Submit a video of you answering 1 interview question.",
      week: "Wk17",
    },
    {
      id: "bm100-wk24",
      phase: "phase-4-challenges",
      order: 19,
      title: "Pitch Video Challenge — WTB Preparation",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Submit your pitch video in preparation for Walk to Board.",
      week: "Wk18",
    },
    {
      id: "bm100-walk-to-board",
      phase: "phase-4-challenges",
      order: 20,
      title: "Walk to Board — Present to External Leader",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Present to an external leader and confirm your session below.",
      week: "Wk19",
      checklistItems: ["Presented to an external leader"],
    },
    {
      id: "bm100-linkedin-prep",
      phase: "phase-4-challenges",
      order: 21,
      title: "Prep of LinkedIn Brand Video Challenge",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Update your LinkedIn profile and paste the link below.",
      week: "Wk20",
      linkLabel: "LinkedIn profile URL",
    },
    {
      id: "bm100-wk18",
      phase: "phase-4-challenges",
      order: 22,
      title: "Showcasing — LinkedIn Brand Video",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Publish 1 LinkedIn post and paste the link below.",
      week: "Wk21",
      linkLabel: "LinkedIn post URL",
    },
    {
      id: "bm100-wk19",
      phase: "phase-4-challenges",
      order: 23,
      title: "Prep of Super Power Challenge Video",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your Super Power Table below — fill every block before submitting.",
      week: "Wk22",
    },
    {
      id: "bm100-wk23",
      phase: "phase-4-challenges",
      order: 24,
      title: "Showcasing — Speak Like a CEO Challenge",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Describe time saved through ERRC and 1 new initiative you started.",
      week: "Wk23",
      placeholder: "Time saved and new initiative…",
    },
    {
      id: "bm100-wk26",
      phase: "graduation",
      order: 25,
      title: "Graduation Ceremony",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Submit one speech video (reference: C-Suite video).",
      week: "Wk24",
    },
  ],
  [PROGRAMS.MBW]: [
    {
      id: "mbw-orientation",
      phase: "pre-preparation",
      order: 0,
      title: "Orientation Session by Rajesh (Live session recording)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the orientation session to begin your MBW journey.",
      week: "Orientation",
    },
    {
      id: "mbw-principles",
      phase: "pre-preparation",
      order: 1,
      title: "27 Principles Video",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Watch the video, then submit 3 key learnings.",
      week: "Wk1-12",
      placeholder: "Enter your 3 key learnings…",
    },
    {
      id: "mbw-csuite",
      phase: "pre-preparation",
      order: 2,
      title: "C-Suite Talk - Topic Finalization",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Watch the session and submit your chosen talk topic for review.",
      week: "Wk1-11",
      placeholder: "Your chosen C-Suite talk topic…",
    },
    {
      id: "mbw-errc",
      phase: "pre-preparation",
      order: 3,
      title: "ERRC — Watch Video",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Watch the ERRC video, then fill your activity grid (editable anytime).",
      week: "Wk1-10",
    },
    {
      id: "mbw-linkedin-profile",
      phase: "pre-preparation",
      order: 4,
      title: "LinkedIn Video Challenge",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Update your LinkedIn profile, then paste your profile URL here.",
      week: "Wk1-9",
      linkLabel: "LinkedIn profile URL",
    },
    {
      id: "mbw-linkedin-connects",
      phase: "pre-preparation",
      order: 5,
      title: "LinkedIn % Connects",
      type: TASK_TYPES.RECURRING_POST,
      kind: "Post",
      description: "Post on LinkedIn weekly and paste your post link. Builds your leadership brand.",
      week: "Wk1-8",
    },
    {
      id: "mbw-objectives",
      phase: "pre-preparation",
      order: 6,
      title: "Objectives",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Write your personal objectives — your Bhag.",
      week: "Wk1-7",
      placeholder: "Your objectives…",
    },
    {
      id: "mbw-resume",
      phase: "pre-preparation",
      order: 7,
      title: "Resume Preparation Video",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Watch the guidance video, then upload your updated resume when ready.",
      week: "Wk1-6",
    },
    {
      id: "mbw-mirror",
      phase: "pre-preparation",
      order: 8,
      title: "Mirror Practice",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record your mirror practice in the LMS or upload a video file.",
      week: "Wk1-5",
    },
    {
      id: "mbw-live-session",
      phase: "pre-preparation",
      order: 9,
      title: "Preparation Session by Suvarna (Live session recording)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Attend / watch the live session recording.",
      week: "Live",
    },
    {
      id: "mbw-commitment",
      phase: "pre-preparation",
      order: 10,
      title: "Your commitment for the session",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record your commitment for the session in the LMS, or upload a video file.",
      week: "Live",
    },
    {
      id: "mbw-drama-huddle",
      phase: "pre-preparation",
      order: 11,
      title: "C-Suite Drama Session Huddle (Live session recording)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the C-Suite Drama session huddle recording.",
      week: "Live",
    },
    {
      id: "mbw-lep",
      phase: "pre-preparation",
      order: 12,
      title: "LEP 5 Rituals Video",
      type: TASK_TYPES.CHECKLIST,
      kind: "Checklist",
      description: "Complete each practice and tick it off — your progress is saved automatically.",
      week: "LEP",
      checklistItems: ["Mirror work","A game","Powerful request","Gratitude"],
    },
    {
      id: "mbw-networking-continued",
      phase: "pre-preparation",
      order: 13,
      title: "LinkedIn Post",
      type: TASK_TYPES.RECURRING_POST,
      kind: "Post",
      description: "Continue networking — submit 2 LinkedIn post links this week.",
      week: "Networking",
    },
    {
      id: "mbw-powerful-request",
      phase: "pre-preparation",
      order: 14,
      title: "Powerful Request Video",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Powerful Request video.",
      week: "Wk1-12",
    },
    {
      id: "q1-csuite-resume",
      phase: "quarter-1",
      order: 100,
      title: "C-Suite Resume",
      type: TASK_TYPES.FILE_UPLOAD,
      kind: "Assignment",
      description: "Upload your updated C-Suite Resume.",
      week: "Wk1",
    },
    {
      id: "q1-linkedin-update",
      phase: "quarter-1",
      order: 101,
      title: "LinkedIn Profile — C-Suite Update",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Update your LinkedIn About section with your 50-word introduction, key accomplishment stories, specialization, and future vision. Share your updated profile link.",
      week: "Wk2",
      linkLabel: "Updated LinkedIn profile URL",
    },
    {
      id: "q1-session1",
      phase: "quarter-1",
      order: 102,
      title: "Impact Champions: LinkedIn Profile & Post",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Attend / watch the Impact Champions session on LinkedIn Profile and Post.",
      week: "Session 1",
    },
    {
      id: "q1-linkedin-posts",
      phase: "quarter-1",
      order: 103,
      title: "LinkedIn Posts (×2)",
      type: TASK_TYPES.RECURRING_POST,
      kind: "Post",
      description: "Write 2 powerful LinkedIn posts this week and submit both links.",
      week: "Wk3",
    },
    {
      id: "q1-csuite-story",
      phase: "quarter-1",
      order: 104,
      title: "C-Suite Story",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Share 3 key accomplishment stories — fill every block below.",
      week: "Wk4",
    },
    {
      id: "q1-session2",
      phase: "quarter-1",
      order: 105,
      title: "Impact Champions: C-Suite Story Video",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on C-Suite Story Video.",
      week: "Session 2",
    },
    {
      id: "q1-story-video",
      phase: "quarter-1",
      order: 106,
      title: "C-Suite Story Video",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record a short video sharing one of your accomplishment stories and share it in the group.",
      week: "Wk5",
    },
    {
      id: "q1-bell-curve",
      phase: "quarter-1",
      order: 107,
      title: "Your Position in the Bell Curve",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete the Bell Curve Position worksheet below — fill every block before submitting.",
      week: "Wk6",
    },
    {
      id: "q1-suvarna-session",
      phase: "quarter-1",
      order: 108,
      title: "Strengthening Your Strengths (by Suvarna)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Attend / watch the session with Suvarna on Strengthening Your Strengths.",
      week: "Session (Suvarna)",
    },
    {
      id: "q1-business-language",
      phase: "quarter-1",
      order: 109,
      title: "Business Language",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record a video answering 3 leadership questions as a C-Suite Leader using business language.",
      week: "Wk7",
    },
    {
      id: "q1-milestone-table",
      phase: "quarter-1",
      order: 110,
      title: "Milestone Table (Delta 2)",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your Delta / Milestone Table below — fill every block before submitting.",
      week: "Wk8",
    },
    {
      id: "q1-session3",
      phase: "quarter-1",
      order: 111,
      title: "Impact Champion: Video CV & C-Suite Application",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champion session on Video CV and applying for C-Suite roles.",
      week: "Session 3",
    },
    {
      id: "q1-video-cv",
      phase: "quarter-1",
      order: 112,
      title: "Video CV",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record and share your Video CV.",
      week: "Wk9",
    },
    {
      id: "q1-apply-csuite",
      phase: "quarter-1",
      order: 113,
      title: "Apply for 1 C-Suite Job",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Apply for at least one C-Suite role and update your status here.",
      week: "Wk10",
      placeholder: "Job title & company I applied to, and current status…",
    },
    {
      id: "q1-session4",
      phase: "quarter-1",
      order: 114,
      title: "Impact Champions: Revisit Super Power",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on revisiting your Super Power.",
      week: "Session 4",
    },
    {
      id: "q1-super-power-table",
      phase: "quarter-1",
      order: 115,
      title: "Super Power Table",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your Super Power Table below — fill every block before submitting.",
      week: "Wk11",
    },
    {
      id: "q1-progress-report",
      phase: "quarter-1",
      order: 116,
      title: "Q1 Progress Report",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Share your progress report covering: C-Suite CV & LinkedIn, C-Suite Story, your position in your growth journey, Milestone Table, and Business Language.",
      week: "Wk12",
      placeholder: "1. C-Suite CV & LinkedIn:\n2. C-Suite Story:\n3. Growth journey position:\n4. Milestone Table:\n5. Business Language:",
    },
    {
      id: "q2-differentiation",
      phase: "quarter-2",
      order: 200,
      title: "Differentiation Statement",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Assess the situation, identify your enemy, and record a 30-second video of one statement that differentiates you against your enemy.",
      week: "Wk13",
    },
    {
      id: "q2-apply-connects",
      phase: "quarter-2",
      order: 201,
      title: "Resume Review + Apply + 3 Connects",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Get your resume reviewed in your group, apply for C-Suite positions, and reach out to 3 business owners/C-Suite leaders. Share update on connects/job application status.",
      week: "Wk14",
      placeholder: "Resume review feedback:\n\nJobs applied to:\n\n3 connects made:",
    },
    {
      id: "q2-session5",
      phase: "quarter-2",
      order: 202,
      title: "Impact Champions: Pitch Video",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Pitch Video.",
      week: "Session 5",
    },
    {
      id: "q2-pitch-video",
      phase: "quarter-2",
      order: 203,
      title: "Pitch Video (1.5 mins)",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Define your problem statement and record a 1.5-minute pitch video.",
      week: "Wk15",
    },
    {
      id: "q2-buddy-rejection",
      phase: "quarter-2",
      order: 204,
      title: "Buddy Rejection Practice",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Practice with your buddy — you pitch and your buddy rejects. Practice your response and try to convince them. Share your key learnings.",
      week: "Wk16",
      placeholder: "Key learnings from the buddy rejection practice…",
    },
    {
      id: "q2-session6",
      phase: "quarter-2",
      order: 205,
      title: "Impact Champions: Strategy Revision",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Strategy Revision.",
      week: "Session 6",
    },
    {
      id: "q2-strategy-draft",
      phase: "quarter-2",
      order: 206,
      title: "Strategy — First Draft",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your strategy document below — fill every required block before submitting.",
      week: "Wk17",
    },
    {
      id: "q2-super-powers-video",
      phase: "quarter-2",
      order: 207,
      title: "Super Powers in Action",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Revisit your super powers and use them this week. Record a short video on which super powers you used.",
      week: "Wk18",
    },
    {
      id: "q2-suvarna-session",
      phase: "quarter-2",
      order: 208,
      title: "Deception/Drama Revision (by Suvarna)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the session with Suvarna on Deception/Drama Revision.",
      week: "Session (Suvarna)",
    },
    {
      id: "q2-drama-practice",
      phase: "quarter-2",
      order: 209,
      title: "Drama Practice — Live",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Practice Drama live. Share the drama you did this week and the experience you had in 3 lines.",
      week: "Wk19",
      placeholder: "The drama I practiced:\n\nMy experience (3 lines):",
    },
    {
      id: "q2-errc-delegation",
      phase: "quarter-2",
      order: 210,
      title: "ERRC Revisit — Delegation",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Revisit your ERRC using upward/sideways delegation. Share the amount of time saved and new activities started.",
      week: "Wk20",
      placeholder: "Time saved:\n\nNew activities started:",
    },
    {
      id: "q2-session7",
      phase: "quarter-2",
      order: 211,
      title: "Impact Champions: Networking",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Networking (LinkedIn Profile & Connect).",
      week: "Session 7",
    },
    {
      id: "q2-linkedin-daily",
      phase: "quarter-2",
      order: 212,
      title: "LinkedIn Post Challenge (Daily)",
      type: TASK_TYPES.RECURRING_POST,
      kind: "Post",
      description: "1 LinkedIn post daily for this week. Submit all 7 post links.",
      week: "Wk21",
    },
    {
      id: "q2-delta2-revisit",
      phase: "quarter-2",
      order: 213,
      title: "Delta 2 + Milestone Table",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Update your Delta / Milestone Table below — fill every block including Kaizen before submitting.",
      week: "Wk22",
    },
    {
      id: "q2-session8",
      phase: "quarter-2",
      order: 214,
      title: "Impact Champions: C-Suite Talk Preparation",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Preparation for C-Suite Talk.",
      week: "Session 8",
    },
    {
      id: "q2-csuite-talk-practice",
      phase: "quarter-2",
      order: 215,
      title: "C-Suite Talk Practice (Buddy)",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Practice your C-Suite talk with your buddy. Record a short video of your topic and preparation steps.",
      week: "Wk23",
    },
    {
      id: "q2-progress-report",
      phase: "quarter-2",
      order: 216,
      title: "Q2 Progress Report",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Share your Q2 progress report.",
      week: "Wk24",
      placeholder: "Q2 progress report:",
    },
    {
      id: "q3-interview-mock",
      phase: "quarter-3",
      order: 300,
      title: "C-Suite Interview Mock Video",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record a video answering 3 C-Suite interview questions based on a JD specific to your profile.",
      week: "Wk25",
    },
    {
      id: "q3-terrain",
      phase: "quarter-3",
      order: 301,
      title: "Terrain Assessment",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Assess your terrain — identify your enemy, energy center, and business goal relevant to you. Share 2 key actions you will take this week.",
      week: "Wk26",
      placeholder: "Enemy:\nEnergy center:\nBusiness goal:\n\n2 key actions:",
    },
    {
      id: "q3-session9",
      phase: "quarter-3",
      order: 302,
      title: "Impact Champions: Business Perspective",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Business Perspective — aligning situations, proposals, and stories to business parameters.",
      week: "Session 9",
    },
    {
      id: "q3-business-language-video",
      phase: "quarter-3",
      order: 303,
      title: "Business Language Video (2 mins)",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record a 2-minute video sharing a new idea, proposal, or introduction using business language.",
      week: "Wk27",
    },
    {
      id: "q3-linkedin-video",
      phase: "quarter-3",
      order: 304,
      title: "LinkedIn Video Challenge",
      type: TASK_TYPES.LINK,
      kind: "Link",
      description: "Make at least one video and share it on LinkedIn. Paste the LinkedIn post link here.",
      week: "Wk28",
      linkLabel: "LinkedIn video post URL",
    },
    {
      id: "q3-session10",
      phase: "quarter-3",
      order: 305,
      title: "Impact Champions: Energy Centers",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Revision of Energy Centers.",
      week: "Session 10",
    },
    {
      id: "q3-energy-centers",
      phase: "quarter-3",
      order: 306,
      title: "Energy Centers Action Plan",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Identify key energy centers and create your action plan to collaborate with them.",
      week: "Wk29",
      placeholder: "Key energy centers:\n\nAction plan to collaborate:",
    },
    {
      id: "q3-book-video",
      phase: "quarter-3",
      order: 307,
      title: "Book Learning Video",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Record a short video explaining a learning from any book as if you are the author.",
      week: "Wk30",
    },
    {
      id: "q3-suvarna-session",
      phase: "quarter-3",
      order: 308,
      title: "Influencing Tactics (by Suvarna)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the session with Suvarna on Revision of Influencing Tactics.",
      week: "Session (Suvarna)",
    },
    {
      id: "q3-role-play",
      phase: "quarter-3",
      order: 309,
      title: "Role Play with Buddy",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Practice a role play with your buddy — suggest an idea and convince your boss/customer using influencing tactics. Share your experience.",
      week: "Wk31",
      placeholder: "My role play scenario:\n\nInfluencing tactics used:\n\nExperience:",
    },
    {
      id: "q3-signalling-video",
      phase: "quarter-3",
      order: 310,
      title: "Direct & Indirect Signalling",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Practice direct and indirect signalling. Record a video explaining one scenario and your way of indirect signalling in that scenario.",
      week: "Wk32",
    },
    {
      id: "q3-session11",
      phase: "quarter-3",
      order: 311,
      title: "Impact Champions: Offence & Defence",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Revision of Offence and Defence Game.",
      week: "Session 11",
    },
    {
      id: "q3-game-plan",
      phase: "quarter-3",
      order: 312,
      title: "Game Plan",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Make your game plan based on your current situation.",
      week: "Wk33",
      placeholder: "My current situation:\n\nGame plan:",
    },
    {
      id: "q3-delta2-revisit",
      phase: "quarter-3",
      order: 313,
      title: "Delta 2 + Milestone Table Revisit",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Update your Delta / Milestone Table below — fill every block with your progress and future commitment.",
      week: "Wk34",
    },
    {
      id: "q3-session12",
      phase: "quarter-3",
      order: 314,
      title: "Impact Champions: C-Suite Mock Interview",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on C-Suite Mock Interview.",
      week: "Session 12",
    },
    {
      id: "q3-csuite-talk-prep",
      phase: "quarter-3",
      order: 315,
      title: "C-Suite Talk Preparation",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Prepare your C-Suite Talk. Share the topic and script.",
      week: "Wk35",
      placeholder: "Topic:\n\nScript:",
    },
    {
      id: "q3-progress-report",
      phase: "quarter-3",
      order: 316,
      title: "Q3 Progress Report",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Share your Q3 progress report.",
      week: "Wk36",
      placeholder: "Q3 progress report:",
    },
    {
      id: "q4-linkedin-reposition",
      phase: "quarter-4",
      order: 400,
      title: "LinkedIn Repositioning (×2 Posts)",
      type: TASK_TYPES.RECURRING_POST,
      kind: "Post",
      description: "Update your LinkedIn profile and post topics as per your repositioning. Share 2 posts from a new angle this week.",
      week: "Wk37",
    },
    {
      id: "q4-errc-revision",
      phase: "quarter-4",
      order: 401,
      title: "ERRC Revision",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Revise your ERRC. Share time saved and new things created.",
      week: "Wk38",
      placeholder: "Time saved:\n\nNew things created:",
    },
    {
      id: "q4-session13",
      phase: "quarter-4",
      order: 402,
      title: "Impact Champions: Bell Curve Revision",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Revision of Bell Curve.",
      week: "Session 13",
    },
    {
      id: "q4-bell-curve-game-plan",
      phase: "quarter-4",
      order: 403,
      title: "Bell Curve + C-Suite Game Plan",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Revisit your bell curve position and complete your C-Suite game plan below.",
      week: "Wk39",
    },
    {
      id: "q4-projection-practice",
      phase: "quarter-4",
      order: 404,
      title: "Projection Practice",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Take one success scenario and one failure scenario — practice projection in each. Share key takeaways.",
      week: "Wk40",
      placeholder: "Success scenario projection:\n\nFailure scenario projection:\n\nKey takeaways:",
    },
    {
      id: "q4-session14",
      phase: "quarter-4",
      order: 405,
      title: "Impact Champions: Enemy-Based Strategy",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Revision of Enemy-Based Strategy.",
      week: "Session 14",
    },
    {
      id: "q4-delta2-video",
      phase: "quarter-4",
      order: 406,
      title: "Delta 2 Progress Video",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Review your Delta 2 Table progress so far. Record a short video updating your progress using business language.",
      week: "Wk41",
    },
    {
      id: "q4-multi-view-strategy",
      phase: "quarter-4",
      order: 407,
      title: "Multi-View Strategy",
      type: TASK_TYPES.EDITABLE_TEMPLATE,
      kind: "Form",
      description: "Complete your multi-view strategy document below — fill every required block before submitting.",
      week: "Wk42",
    },
    {
      id: "q4-suvarna-session",
      phase: "quarter-4",
      order: 408,
      title: "C-Suite Game Plan (by Suvarna)",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the session with Suvarna on C-Suite Game Plan.",
      week: "Session (Suvarna)",
    },
    {
      id: "q4-csuite-game-plan",
      phase: "quarter-4",
      order: 409,
      title: "C-Suite Game Plan",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Create your C-Suite game plan for one scenario.",
      week: "Wk43",
      placeholder: "Scenario:\n\nC-Suite game plan:",
    },
    {
      id: "q4-challenges",
      phase: "quarter-4",
      order: 410,
      title: "Challenges Assessment",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Assess the surroundings and make a list of challenges.",
      week: "Wk44",
      placeholder: "List of challenges:",
    },
    {
      id: "q4-session15",
      phase: "quarter-4",
      order: 411,
      title: "Impact Champions: Drama & Deception",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Drama/Deception.",
      week: "Session 15",
    },
    {
      id: "q4-drama-video",
      phase: "quarter-4",
      order: 412,
      title: "Drama Situations Practice",
      type: TASK_TYPES.VIDEO_RECORD,
      kind: "Video",
      description: "Practice drama — take 3 situations and practice in mirror how to do drama. Record a video of at least one drama situation.",
      week: "Wk45",
    },
    {
      id: "q4-rejection-practice",
      phase: "quarter-4",
      order: 413,
      title: "Pitch Rejection Scenario (Buddy)",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Practice the rejection scenario for your pitch with your buddy. Share your experience.",
      week: "Wk46",
      placeholder: "My experience from the rejection practice:",
    },
    {
      id: "q4-session16",
      phase: "quarter-4",
      order: 414,
      title: "Impact Champions: ERRC Revision",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Watch the Impact Champions session on Revision of ERRC.",
      week: "Session 16",
    },
    {
      id: "q4-final-errc",
      phase: "quarter-4",
      order: 415,
      title: "Final ERRC Revision",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Revise your ERRC. Share time saved and new things created.",
      week: "Wk47",
      placeholder: "Time saved:\n\nNew things created:",
    },
    {
      id: "q4-apply-csuite",
      phase: "quarter-4",
      order: 416,
      title: "Apply for C-Suite Position",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Apply for a C-Suite position and share your experience.",
      week: "Wk48",
      placeholder: "Position applied for:\n\nMy experience:",
    },
    {
      id: "grad-prep-1",
      phase: "graduation",
      order: 500,
      title: "Graduation Preparation — Week 1",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Begin preparing for graduation. Document your key milestones and achievements from the program.",
      week: "Wk49",
      placeholder: "Key milestones achieved:\n\nPreparation notes:",
    },
    {
      id: "grad-prep-2",
      phase: "graduation",
      order: 501,
      title: "Graduation Preparation — Week 2",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Continue preparing for graduation. Refine your C-Suite story and talk.",
      week: "Wk50",
      placeholder: "C-Suite story refinement:\n\nTalk preparation:",
    },
    {
      id: "grad-prep-3",
      phase: "graduation",
      order: 502,
      title: "Graduation Preparation — Week 3",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Final preparation for graduation. Review all deliverables and get ready to present.",
      week: "Wk51",
      placeholder: "Final preparation notes:",
    },
    {
      id: "grad-prep-4",
      phase: "graduation",
      order: 503,
      title: "Graduation Preparation — Week 4",
      type: TASK_TYPES.TEXT,
      kind: "Write",
      description: "Complete all final preparations for your graduation ceremony.",
      week: "Wk52",
      placeholder: "Completion checklist and notes:",
    },
    {
      id: "grad-ceremony",
      phase: "graduation",
      order: 504,
      title: "Graduation Ceremony",
      type: TASK_TYPES.WATCH_ONLY,
      kind: "Watch",
      description: "Attend your MBW Graduation Ceremony — celebrate the completion of your C-Suite journey!",
      week: "Graduation",
    },
  ],
};

export const COURSE_LABEL = {
  [PROGRAMS.LEP]: 'Leadership Essentials',
  [PROGRAMS.BM100]: '100 Board Members',
  [PROGRAMS.MBW]: 'Master of Business Warfare',
};

export function coursePhases(programId) {
  return COURSE_PHASES[programId] || [];
}

export function courseTasks(programId, phaseId) {
  return (COURSE_TASKS[programId] || [])
    .filter((t) => !phaseId || t.phase === phaseId)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

export function courseTask(programId, taskId) {
  return (COURSE_TASKS[programId] || []).find((t) => t.id === taskId) || null;
}

export function coursePhase(programId, phaseId) {
  return coursePhases(programId).find((p) => p.id === phaseId) || null;
}

export function isPhaseOpen(phase, enrolled) {
  if (enrolled) return true;
  return !!phase?.openRegistered;
}

export function currentPhaseId(programId, enrolled) {
  if (programId === PROGRAMS.LEP) return enrolled ? 'day-2' : 'pre-program';
  if (programId === PROGRAMS.BM100) return enrolled ? 'phase-2-pitch-strategy' : 'onboarding';
  if (programId === PROGRAMS.MBW) return enrolled ? 'quarter-1' : 'pre-preparation';
  return coursePhases(programId)[0]?.id || null;
}

export function nextCourseTask(programId, taskId) {
  const task = courseTask(programId, taskId);
  if (!task) return null;
  const list = courseTasks(programId, task.phase);
  const i = list.findIndex((t) => t.id === taskId);
  return i >= 0 && i < list.length - 1 ? list[i + 1] : null;
}
